config/routes.rb
Rails.application.routes.draw do

  resources :events
  get 'login', to: 'login#new', :as => :login
  post 'login', to: 'login#create'
  get 'logout', to: 'login#destroy', :as => :logout
  get 'events/:id/signup', to: 'events#sign_up', :as => :sign_up_event

  resources :users
  get 'welcome/index'
  get 'users/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user,  :foreign_key => :owner_id
	has_many :event_users
	has_many :users, :through => :event_users

	validates :name, presence: true
	validates :date, presence: true
	validates :max_participants, presence: true

	validate :cannot_have_more_participants_than_max
	validate :cannot_be_before_now
	private

		def cannot_have_more_participants_than_max
			if max_participants < users.length
				errors.add(:max_participants, "cannot be less than current number of participants")
			end
		end

		def cannot_be_before_now
			if date <= DateTime.now
				errors.add(:date, "Event's date cannot be set before now")
			end
		end
end

app/models/event_user.rb
class EventUser < ApplicationRecord
	belongs_to :event
	belongs_to :user
	validates_uniqueness_of :user_id, :scope => [:event_id]
end

app/models/user.rb
class User < ApplicationRecord
	require 'digest/sha1'
	#before_save :encrypt_password
	has_secure_password
	
	has_many :events, :foreign_key => :owner_id
	has_many :event_users
	has_many :events, :through => :event_users

	validates :email, presence: true, :uniqueness => true
	validates :first_name, presence: true
	validates :last_name, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper :all
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :sign_up]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.owner_id = session[:user_id]
    respond_to do |format|
      if @event.save
        users = User.all
        users.each do |user|
          UserMailer.new_event_email(user, @event).deliver
        end 
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    if @event.owner_id == session[:user_id] 
      @event.destroy
      respond_to do |format|
        format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { redirect_to events_url, notice: 'You can only delete events you are the owner of.' }
    end
  end

  def sign_up
    if @event.max_participants - @event.users.length > 0
      begin
        user = User.find(session[:user_id])
        @event.users << user
      rescue ActiveRecord::RecordInvalid => invalid
        flash[:alert] = "You already signed up to participate in this event"
      end
    else 
      flash[:notice] = "Sorry, this event already has a maximum number of participants"
    end
    redirect_to @event
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :place, :date, :max_participants)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
	user = User.where(email: params[:email]).first
	if user && user.authenticate(params[:password])
	  login_user!(user)
	else
	  flash[:notice] = "Invalid email or password"
	  redirect_to login_path
	end
  end

  def destroy
  	session[:user_id] = nil
  	session[:user_email] = nil
  	flash[:notice] = "Logged out successfully"
 	redirect_to root_path
  end

  private

	def login_user!(user)
	  session[:user_email] = user.email
	  session[:user_id] = user.id
	  flash[:notice] = "Welcome, you're now logged in"
	  redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    if @user.id == session[:user_id]
      @user.destroy
      respond_to do |format|
        session[:user_id] = nil
        session[:user_email] = nil
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      format.html { redirect_to users_url, notice: 'You can only delete your own account.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :first_name, :last_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
  		User.find(session[:user_id]) if session[:user_id]
  	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :place %>
    <%= f.text_field :place %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :max_participants %>
    <%= f.number_field :max_participants %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Place</th>
      <th>Date</th>
      <th>Owner</th>
      <th>Max participants</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.place %></td>
        <td><%= event.date %></td>
        <td><%= event.owner_id %></td>
        <td><%= event.max_participants %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<%if current_user %>
	<h1>New Event</h1>

	<%= render 'form', event: @event %>

	<%= link_to 'Back', events_path %>
<% else %>
	<h1>Sorry, you have no access to this site. Please <%= link_to "log in", controller: "login", action: "new" %> to continue </h1>
<% end %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Place:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Owner:</strong>
  <% user = User.find(@event.owner_id) %>
  <%= user.first_name %> <%= user.last_name %>
</p>

<p>
  <strong>Max participants:</strong>
  <%= @event.max_participants %>
</p>

<p>
  <strong>Open slots:</strong>
  <%= @event.max_participants - @event.users.length %>
</p>

<strong>Participating</strong>
<ul>
  <% @event.users.each do |user| %>
    <li><%= user.first_name %> <%= user.last_name  %></li>
  <% end %>

</ul>
<%= link_to 'Sign up for this event', sign_up_event_path(@event) %> </br>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeeUAgain</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/create.html.erb
<h1>Login#create</h1>
<p>Find me in app/views/login/create.html.erb</p>

app/views/login/new.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag(:action => 'create') do %>
    <p>Email:</br> <%= text_field_tag(:email) %></p> 
    <p>Password:</br> <%= password_field_tag :password %></p> 
    <%= submit_tag("Log In") %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<% if current_user %>
	<p>logged in as <%= current_user.email %></p>
<% else %>
	<p> Please <%= link_to "log in", controller: "login", action: "new" %> </p>
<% end %>